data:
  dir: /mnt/c/Users/amehedi/Downloads/ml_debris/output/thomas
  target_name: dem_diff.tif
  include_glob: "*.tif"
  exclude_contains:
    - pred
  exclude_names:
    - dem_pre.tif
    - dem_post.tif

split:
  test_size: 0.2
  random_state: 42

model:
  type: xgb
  n_estimators: 1200
  max_depth: 6
  learning_rate: 0.03
  subsample: 0.9
  colsample_bytree: 0.9
  min_child_weight: 5.0
  gamma: 0.1
  reg_alpha: 0.0
  reg_lambda: 2.0
  tree_method: hist
  max_bin: 256
  verbosity: 0
  random_state: 42
  n_jobs: -1

output:
  model_dir: models/xgb
  run_prefix: xgb
