data:
  dir: /mnt/c/Users/amehedi/Downloads/ml_debris/output/thomas
  target_name: dem_diff.tif
  include_glob: "*.tif"
  exclude_contains:
    - pred
  exclude_names:
    - dem_pre.tif
    - dem_post.tif

split:
  test_size: 0.2
  random_state: 42

model:
  type: xgb
  n_estimators: 500
  max_depth: 8
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 1.0
  random_state: 42
  n_jobs: -1

output:
  model_dir: models/xgb
  run_prefix: xgb
