data:
  dir: /mnt/c/Users/amehedi/Downloads/ml_debris/output/thomas
  target_name: dem_diff.tif
  include_glob: "*.tif"
  exclude_names:
    - dem_pre.tif
    - dem_post.tif

split:
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 300
  max_depth: null
  min_samples_leaf: 1
  random_state: 42
  n_jobs: -1

output:
  model_dir: models/rf
  run_prefix: rf

